package com.game.questionsanswers.model;

import java.util.ArrayList;
import java.util.List;

public class CapitalQuestions {

    public static List<Question> getQuestions() {
        List<Question> questions = new ArrayList<>();
        questions.add(new Question("¿Cuál es la capital de Francia?", "París"));
        questions.add(new Question("¿Cuál es la capital de Alemania?", "Berlín"));
        questions.add(new Question("¿Cuál es la capital de Italia?", "Roma"));
        questions.add(new Question("¿Cuál es la capital de España?", "Madrid"));
        questions.add(new Question("¿Cuál es la capital de Portugal?", "Lisboa"));
        questions.add(new Question("¿Cuál es la capital de Reino Unido?", "Londres"));
        questions.add(new Question("¿Cuál es la capital de Rusia?", "Moscú"));
        questions.add(new Question("¿Cuál es la capital de Japón?", "Tokio"));
        questions.add(new Question("¿Cuál es la capital de China?", "Pekín"));
        questions.add(new Question("¿Cuál es la capital de Estados Unidos?", "Washington D.C."));
        questions.add(new Question("¿Cuál es la capital de Canadá?", "Ottawa"));
        questions.add(new Question("¿Cuál es la capital de México?", "Ciudad de México"));
        questions.add(new Question("¿Cuál es la capital de Brasil?", "Brasilia"));
        questions.add(new Question("¿Cuál es la capital de Argentina?", "Buenos Aires"));
        questions.add(new Question("¿Cuál es la capital de Colombia?", "Bogotá"));
        questions.add(new Question("¿Cuál es la capital de Perú?", "Lima"));
        questions.add(new Question("¿Cuál es la capital de Chile?", "Santiago"));
        questions.add(new Question("¿Cuál es la capital de Venezuela?", "Caracas"));
        questions.add(new Question("¿Cuál es la capital de Uruguay?", "Montevideo"));
        questions.add(new Question("¿Cuál es la capital de Paraguay?", "Asunción"));
        questions.add(new Question("¿Cuál es la capital de Bolivia?", "Sucre"));
        questions.add(new Question("¿Cuál es la capital de Ecuador?", "Quito"));
        questions.add(new Question("¿Cuál es la capital de Cuba?", "La Habana"));
        questions.add(new Question("¿Cuál es la capital de República Dominicana?", "Santo Domingo"));
        questions.add(new Question("¿Cuál es la capital de Puerto Rico?", "San Juan"));
        questions.add(new Question("¿Cuál es la capital de Costa Rica?", "San José"));
        questions.add(new Question("¿Cuál es la capital de Panamá?", "Ciudad de Panamá"));
        questions.add(new Question("¿Cuál es la capital de Guatemala?", "Ciudad de Guatemala"));
        questions.add(new Question("¿Cuál es la capital de Honduras?", "Tegucigalpa"));
        questions.add(new Question("¿Cuál es la capital de El Salvador?", "San Salvador"));
        questions.add(new Question("¿Cuál es la capital de Nicaragua?", "Managua"));
        questions.add(new Question("¿Cuál es la capital de Belice?", "Belmopán"));
        questions.add(new Question("¿Cuál es la capital de Australia?", "Canberra"));
        questions.add(new Question("¿Cuál es la capital de Nueva Zelanda?", "Wellington"));
        questions.add(new Question("¿Cuál es la capital de Sudáfrica?", "Pretoria"));
        questions.add(new Question("¿Cuál es la capital de Egipto?", "El Cairo"));
        questions.add(new Question("¿Cuál es la capital de Nigeria?", "Abuya"));
        questions.add(new Question("¿Cuál es la capital de Kenia?", "Nairobi"));
        questions.add(new Question("¿Cuál es la capital de Etiopía?", "Addis Abeba"));
        questions.add(new Question("¿Cuál es la capital de Ghana?", "Acra"));
        questions.add(new Question("¿Cuál es la capital de Senegal?", "Dakar"));
        questions.add(new Question("¿Cuál es la capital de Marruecos?", "Rabat"));
        questions.add(new Question("¿Cuál es la capital de Argelia?", "Argel"));
        questions.add(new Question("¿Cuál es la capital de Túnez?", "Túnez"));
        questions.add(new Question("¿Cuál es la capital de Libia?", "Trípoli"));
        questions.add(new Question("¿Cuál es la capital de Sudán?", "Jartum"));
        questions.add(new Question("¿Cuál es la capital de Angola?", "Luanda"));
        questions.add(new Question("¿Cuál es la capital de Mozambique?", "Maputo"));
        questions.add(new Question("¿Cuál es la capital de Madagascar?", "Antananarivo"));
        questions.add(new Question("¿Cuál es la capital de India?", "Nueva Delhi"));
        questions.add(new Question("¿Cuál es la capital de Pakistán?", "Islamabad"));
        questions.add(new Question("¿Cuál es la capital de Bangladesh?", "Daca"));
        questions.add(new Question("¿Cuál es la capital de Sri Lanka?", "Colombo"));
        questions.add(new Question("¿Cuál es la capital de Nepal?", "Katmandú"));
        questions.add(new Question("¿Cuál es la capital de Bután?", "Thimphu"));
        questions.add(new Question("¿Cuál es la capital de Tailandia?", "Bangkok"));
        questions.add(new Question("¿Cuál es la capital de Vietnam?", "Hanoi"));
        questions.add(new Question("¿Cuál es la capital de Malasia?", "Kuala Lumpur"));
        questions.add(new Question("¿Cuál es la capital de Singapur?", "Singapur"));
        questions.add(new Question("¿Cuál es la capital de Indonesia?", "Yakarta"));
        questions.add(new Question("¿Cuál es la capital de Filipinas?", "Manila"));
        questions.add(new Question("¿Cuál es la capital de Camboya?", "Nom Pen"));
        questions.add(new Question("¿Cuál es la capital de Laos?", "Vientián"));
        questions.add(new Question("¿Cuál es la capital de Birmania?", "Naypyidaw"));
        questions.add(new Question("¿Cuál es la capital de Corea del Sur?", "Seúl"));
        questions.add(new Question("¿Cuál es la capital de Corea del Norte?", "Pionyang"));
        questions.add(new Question("¿Cuál es la capital de Mongolia?", "Ulán Bator"));
        questions.add(new Question("¿Cuál es la capital de Turquía?", "Ankara"));
        questions.add(new Question("¿Cuál es la capital de Israel?", "Jerusalén"));
        questions.add(new Question("¿Cuál es la capital de Arabia Saudita?", "Riad"));
        questions.add(new Question("¿Cuál es la capital de Irán?", "Teherán"));
        questions.add(new Question("¿Cuál es la capital de Irak?", "Bagdad"));
        questions.add(new Question("¿Cuál es la capital de Siria?", "Damasco"));
        questions.add(new Question("¿Cuál es la capital de Líbano?", "Beirut"));
        questions.add(new Question("¿Cuál es la capital de Jordania?", "Amán"));
        questions.add(new Question("¿Cuál es la capital de Kuwait?", "Kuwait"));
        questions.add(new Question("¿Cuál es la capital de Omán?", "Mascate"));
        questions.add(new Question("¿Cuál es la capital de Yemen?", "Saná"));
        questions.add(new Question("¿Cuál es la capital de Emiratos Árabes Unidos?", "Abu Dabi"));
        questions.add(new Question("¿Cuál es la capital de Catar?", "Doha"));
        questions.add(new Question("¿Cuál es la capital de Bahréin?", "Manama"));
        questions.add(new Question("¿Cuál es la capital de Uzbekistán?", "Taskent"));
        questions.add(new Question("¿Cuál es la capital de Kazajistán?", "Astaná"));
        questions.add(new Question("¿Cuál es la capital de Kirguistán?", "Biskek"));
        questions.add(new Question("¿Cuál es la capital de Tayikistán?", "Dusambé"));
        questions.add(new Question("¿Cuál es la capital de Turkmenistán?", "Asjabad"));
        questions.add(new Question("¿Cuál es la capital de Afganistán?", "Kabul"));
        questions.add(new Question("¿Cuál es la capital de Georgia?", "Tiflis"));
        questions.add(new Question("¿Cuál es la capital de Armenia?", "Ereván"));
        questions.add(new Question("¿Cuál es la capital de Azerbaiyán?", "Bakú"));
        questions.add(new Question("¿Cuál es la capital de Bielorrusia?", "Minsk"));
        questions.add(new Question("¿Cuál es la capital de Ucrania?", "Kiev"));
        questions.add(new Question("¿Cuál es la capital de Moldavia?", "Chisináu"));
        questions.add(new Question("¿Cuál es la capital de Polonia?", "Varsovia"));
        questions.add(new Question("¿Cuál es la capital de República Checa?", "Praga"));
        questions.add(new Question("¿Cuál es la capital de Eslovaquia?", "Bratislava"));
        questions.add(new Question("¿Cuál es la capital de Hungría?", "Budapest"));
        questions.add(new Question("¿Cuál es la capital de Rumanía?", "Bucarest"));
        questions.add(new Question("¿Cuál es la capital de Bulgaria?", "Sofía"));
        questions.add(new Question("¿Cuál es la capital de Serbia?", "Belgrado"));
        questions.add(new Question("¿Cuál es la capital de Croacia?", "Zagreb"));
        questions.add(new Question("¿Cuál es la capital de Bosnia y Herzegovina?", "Sarajevo"));
        questions.add(new Question("¿Cuál es la capital de Montenegro?", "Podgorica"));
        questions.add(new Question("¿Cuál es la capital de Macedonia del Norte?", "Skopie"));
        questions.add(new Question("¿Cuál es la capital de Albania?", "Tirana"));

        return questions;
    }
}

